name: Clear Cloudflare Cache

on: 
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare Cache
        uses: jsmrcaga/action-cloudflare-cache-purge@v1
        with:
          api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: your-cloudflare-zone-id
